# fly.toml app configuration file generated for peepsignal2 on 2024-04-28T16:30:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'peepsignal2'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 4141
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 4141

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
